spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

initial.data.file=classpath:initial-data.txt
security.password.length=10

management.info.env.enabled=true
info.app.name=Gym CRM API
info.app.description=REST API for gym trainee/trainer/training management
info.app.version=1.0-SNAPSHOT