spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/gym_crm
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

jwt.secret=${JWT_SECRET:gb5yQBGE0dTXg/SRQv6Py01N5UVKrsS4SvuCkVlAFM4=}

hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=update

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

logging.level.org.gymcrm=DEBUG