initial.data.file=classpath:initial-data.txt
security.password.length=10

db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/gym_crm
db.username=${DB_USERNAME:postgres}
db.password=${DB_PASSWORD:postgres}

hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=update
db.pool.maximum-size=10
db.pool.minimum-idle=2