spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

initial.data.file=classpath:initial-data.txt
security.password.length=10

jwt.expiration-ms=${jwt_expiration_ms:3600000}

service.jwt.expiration-ms=60000

management.info.env.enabled=true
info.app.name=Gym CRM API
info.app.description=REST API for gym trainee/trainer/training management
info.app.version=1.0-SNAPSHOT

security.login.max-attempts=3
security.login.lock-duration-minutes=5

spring.application.name=gym-service
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true

resilience4j.circuitbreaker.instances.workloadService.sliding-window-size=10
resilience4j.circuitbreaker.instances.workloadService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.workloadService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.workloadService.permitted-number-of-calls-in-half-open-state=3

resilience4j.retry.instances.workloadService.max-attempts=2
resilience4j.retry.instances.workloadService.wait-duration=500ms

spring.cloud.openfeign.client.config.default.connect-timeout=2000
spring.cloud.openfeign.client.config.default.read-timeout=3000

jms.workload-queue=workload.events