server.port=8080

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:gymcrm;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=

jwt.secret=gb5yQBGE0dTXg/SRQv6Py01N5UVKrsS4SvuCkVlAFM4=
service.jwt.secret=1fZxu+Aap4l/FQda9j+AyFPZ4rhWEpSpsHshfliipgU=

hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=update

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.org.gymcrm=DEBUG
logging.level.org.apache.activemq=ERROR

cors.allowed-origins=*

eureka.client.enabled=false
management.health.jms.enabled=false