server.port=8082
eureka.client.service-url.defaultZone=${EUREKA_URI:http://eureka-dev:8761/eureka/}
eureka.instance.prefer-ip-address=true

spring.data.mongodb.uri=${MONGODB_URI:mongodb://mongo-dev:27017/workload_db}
spring.data.mongodb.auto-index-creation=true

spring.activemq.broker-url=${ACTIVEMQ_BROKER_URL:tcp://activemq-dev:61616}
spring.activemq.user=${ACTIVEMQ_USER}
spring.activemq.password=${ACTIVEMQ_PASSWORD}

jms.listener.concurrency=3-10
activemq.redelivery.max-attempts=2