server.port=8082

spring.data.mongodb.uri=mongodb://localhost:27017/workload_db
spring.data.mongodb.auto-index-creation=false

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

jms.listener.concurrency=1-1
activemq.redelivery.max-attempts=1

service.jwt.secret=1fZxu+Aap4l/FQda9j+AyFPZ4rhWEpSpsHshfliipgU=

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.org.apache.activemq=ERROR
logging.level.org.mongodb.driver=ERROR

eureka.client.enabled=false
management.health.mongo.enabled=false
management.health.jms.enabled=false