server.port=8082
spring.application.name=trainer-workload-service

eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

spring.datasource.url=jdbc:h2:mem:workload_db
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

service.jwt.secret=${SERVICE_JWT_SECRET:1fZxu+Aap4l/FQda9j+AyFPZ4rhWEpSpsHshfliipgU=}

spring.activemq.broker-url=${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
spring.activemq.user=${ACTIVEMQ_USER:admin}
spring.activemq.password=${ACTIVEMQ_PASSWORD:admin}
jms.workload-queue=workload.events

spring.activemq.packages.trust-all=true

spring.jms.listener.session.transacted=true
activemq.redelivery.max-attempts=1