spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

spring.application.name=trainer-workload-service
jms.workload-queue=workload.events
spring.activemq.packages.trust-all=true
spring.jms.listener.session.transacted=true

service.jwt.secret=${SERVICE_JWT_SECRET:1fZxu+Aap4l/FQda9j+AyFPZ4rhWEpSpsHshfliipgU=}